export const OPTIMIZE_DEPS = [
	// core
	"react",
	"react-dom",
	"axios",
	"react-dom/client",
	"react-router-dom",
	// Material UI
	"@mui/material",
	"@mui/icons-material",
	"@mui/x-date-pickers",
	"@emotion/react",
	"@emotion/styled",
	"@mui/x-data-grid",
	"@mui/material/styles",
	"@mui/material/locale",
	"@mui/x-data-grid/locales",
	"@mui/icons-material/Download",
	"@mui/icons-material/Edit",
	"@mui/icons-material/MoreVert",
	"@mui/icons-material/ArrowBack",
	"@mui/icons-material/ChevronRight",
	"@mui/icons-material/People",
	"@mui/icons-material/EventNote",
	"@mui/icons-material/Visibility",
	"@mui/icons-material/VisibilityOff",
	"@tanstack/react-query",
	"zustand",
	"react-hook-form",
	"@hookform/resolvers/yup",
	"yup",
	"@tanstack/react-query-devtools",
	// utils
	"dayjs",
	"dayjs/locale/es",
	"framer-motion",
];
